name: Build and Release

on:
  workflow_dispatch:
    inputs:
      runReleaseAction:
        description: "Run release action"
        required: false
        type: boolean

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: ["windows-latest"]
        python-version: ["3.10"]
        architecture: ['x64']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python  ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          cache: 'pip'

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Build
        run: |
          $PythonRoot = (python -c "import os,sys; print(os.path.dirname(sys.executable))")
          ./build.ps1 -PythonRoot $PythonRoot
        shell: pwsh

      - name: Release
        if: ${{ inputs.runReleaseAction }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.whl
